const getStaff = (service: string) => {
  const staffListings = [
    {
      firstName: "John",
      lastName: "Smith",
      jobTitle: "chef",
      startDate: "03/01/2024",
      endDate: "04/01/2024",
      location: "London",
      experience: "2-5 years",
    },
    {
      firstName: "Emily",
      lastName: "Davies",
      jobTitle: "waiter",
      startDate: "02/15/2024",
      endDate: "03/15/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Marco",
      lastName: "Rossi",
      jobTitle: "chauffeur",
      startDate: "03/10/2024",
      endDate: "04/10/2024",
      location: "Madrid",
      experience: "5-10 years",
    },
    {
      firstName: "Sophie",
      lastName: "Lefèvre",
      jobTitle: "bartender",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Paris",
      experience: "2-5 years",
    },
    {
      firstName: "David",
      lastName: "Brown",
      jobTitle: "manager",
      startDate: "02/20/2024",
      endDate: "03/20/2024",
      location: "London",
      experience: "10+ years",
    },
    {
      firstName: "Elena",
      lastName: "García",
      jobTitle: "performer",
      startDate: "03/15/2024",
      endDate: "04/15/2024",
      location: "Madrid",
      experience: "2-5 years",
    },
    {
      firstName: "Michael",
      lastName: "Thompson",
      jobTitle: "technician",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "London",
      experience: "5-10 years",
    },
    {
      firstName: "Juliette",
      lastName: "Moreau",
      jobTitle: "cleaner",
      startDate: "03/08/2024",
      endDate: "04/08/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Pedro",
      lastName: "Gómez",
      jobTitle: "chef",
      startDate: "03/12/2024",
      endDate: "04/12/2024",
      location: "Madrid",
      experience: "5-10 years",
    },
    {
      firstName: "Olivia",
      lastName: "Turner",
      jobTitle: "waiter",
      startDate: "03/02/2024",
      endDate: "04/02/2024",
      location: "London",
      experience: "0-1 year",
    },
    {
      firstName: "William",
      lastName: "Johnson",
      jobTitle: "technician",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "London",
      experience: "5-10 years",
    },
    {
      firstName: "Charlotte",
      lastName: "Dubois",
      jobTitle: "chef",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "Paris",
      experience: "10+ years",
    },
    {
      firstName: "Gabriel",
      lastName: "Fernández",
      jobTitle: "cleaner",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "Madrid",
      experience: "0-1 year",
    },
    {
      firstName: "Emma",
      lastName: "White",
      jobTitle: "bartender",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "London",
      experience: "2-5 years",
    },
    {
      firstName: "Luis",
      lastName: "Martínez",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "Madrid",
      experience: "10+ years",
    },
    {
      firstName: "Isabella",
      lastName: "Lopez",
      jobTitle: "waiter",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "London",
      experience: "0-1 year",
    },
    {
      firstName: "Lucas",
      lastName: "Girard",
      jobTitle: "manager",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Paris",
      experience: "5-10 years",
    },
    {
      firstName: "Mia",
      lastName: "Brown",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "London",
      experience: "2-5 years",
    },
    {
      firstName: "Noah",
      lastName: "Petit",
      jobTitle: "technician",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "Paris",
      experience: "5-10 years",
    },
    {
      firstName: "Amelia",
      lastName: "King",
      jobTitle: "chef",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "London",
      experience: "5-10 years",
    },
    {
      firstName: "Yusuf",
      lastName: "Kaya",
      jobTitle: "chef",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Aylin",
      lastName: "Arslan",
      jobTitle: "waiter",
      startDate: "03/10/2024",
      endDate: "04/10/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "Emir",
      lastName: "Yılmaz",
      jobTitle: "chauffeur",
      startDate: "03/15/2024",
      endDate: "04/15/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Nazlı",
      lastName: "Öztürk",
      jobTitle: "bartender",
      startDate: "03/20/2024",
      endDate: "04/20/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Kaan",
      lastName: "Demir",
      jobTitle: "manager",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "Istanbul",
      experience: "10+ years",
    },
    {
      firstName: "Aslı",
      lastName: "Çelik",
      jobTitle: "performer",
      startDate: "03/01/2024",
      endDate: "04/01/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "Deniz",
      lastName: "Albayrak",
      jobTitle: "technician",
      startDate: "03/08/2024",
      endDate: "04/08/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Gizem",
      lastName: "Koç",
      jobTitle: "cleaner",
      startDate: "03/12/2024",
      endDate: "04/12/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Ege",
      lastName: "Şahin",
      jobTitle: "chef",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Berk",
      lastName: "Türk",
      jobTitle: "waiter",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Ali",
      lastName: "Kaya",
      jobTitle: "technician",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Ayşe",
      lastName: "Yılmaz",
      jobTitle: "chef",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "Istanbul",
      experience: "10+ years",
    },
    {
      firstName: "Mehmet",
      lastName: "Arslan",
      jobTitle: "cleaner",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "Fatma",
      lastName: "Demir",
      jobTitle: "bartender",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Mustafa",
      lastName: "Şahin",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "Istanbul",
      experience: "10+ years",
    },
    {
      firstName: "Zeynep",
      lastName: "Koç",
      jobTitle: "waiter",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "İsmail",
      lastName: "Aydın",
      jobTitle: "manager",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Emine",
      lastName: "Şen",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Hüseyin",
      lastName: "Kurt",
      jobTitle: "technician",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Seda",
      lastName: "Öztürk",
      jobTitle: "chef",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Eren",
      lastName: "Kılıç",
      jobTitle: "bartender",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Selma",
      lastName: "Çetin",
      jobTitle: "cleaner",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "Kaan",
      lastName: "Yıldız",
      jobTitle: "waiter",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "Aslı",
      lastName: "Kurtuluş",
      jobTitle: "manager",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Berk",
      lastName: "Toprak",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Nazlı",
      lastName: "Güneş",
      jobTitle: "technician",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Can",
      lastName: "Karadağ",
      jobTitle: "chef",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Istanbul",
      experience: "10+ years",
    },
    {
      firstName: "Elif",
      lastName: "Yılmazer",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Deniz",
      lastName: "Aydın",
      jobTitle: "waiter",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "Şevval",
      lastName: "Demir",
      jobTitle: "cleaner",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "Luc",
      lastName: "Dupont",
      jobTitle: "waiter",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Camille",
      lastName: "Leroux",
      jobTitle: "chef",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "Paris",
      experience: "10+ years",
    },
    {
      firstName: "Théo",
      lastName: "Martel",
      jobTitle: "cleaner",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Juliette",
      lastName: "Renard",
      jobTitle: "bartender",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "Paris",
      experience: "2-5 years",
    },
    {
      firstName: "Louis",
      lastName: "Lefèvre",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "Paris",
      experience: "10+ years",
    },
    {
      firstName: "Manon",
      lastName: "Girard",
      jobTitle: "manager",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "Paris",
      experience: "5-10 years",
    },
    {
      firstName: "Gabriel",
      lastName: "Dubois",
      jobTitle: "technician",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Paris",
      experience: "5-10 years",
    },
    {
      firstName: "Emma",
      lastName: "Roy",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "Paris",
      experience: "2-5 years",
    },
    {
      firstName: "Chloé",
      lastName: "Fournier",
      jobTitle: "waiter",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Lucas",
      lastName: "Lambert",
      jobTitle: "chef",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "Paris",
      experience: "5-10 years",
    },
    {
      firstName: "Luc",
      lastName: "Dupont",
      jobTitle: "waiter",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Camille",
      lastName: "Leroux",
      jobTitle: "chef",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "Paris",
      experience: "10+ years",
    },
    {
      firstName: "Théo",
      lastName: "Martel",
      jobTitle: "cleaner",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Juliette",
      lastName: "Renard",
      jobTitle: "bartender",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "Paris",
      experience: "2-5 years",
    },
    {
      firstName: "Louis",
      lastName: "Lefèvre",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "Paris",
      experience: "10+ years",
    },
    {
      firstName: "Manon",
      lastName: "Girard",
      jobTitle: "manager",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "Paris",
      experience: "5-10 years",
    },
    {
      firstName: "Gabriel",
      lastName: "Dubois",
      jobTitle: "technician",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Paris",
      experience: "5-10 years",
    },
    {
      firstName: "Emma",
      lastName: "Roy",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "Paris",
      experience: "2-5 years",
    },
    {
      firstName: "Chloé",
      lastName: "Fournier",
      jobTitle: "waiter",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Lucas",
      lastName: "Lambert",
      jobTitle: "chef",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "Paris",
      experience: "5-10 years",
    },
    {
      firstName: "Sophia",
      lastName: "Evans",
      jobTitle: "waiter",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "London",
      experience: "0-1 year",
    },
    {
      firstName: "Oliver",
      lastName: "Wilson",
      jobTitle: "chef",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "London",
      experience: "10+ years",
    },
    {
      firstName: "Amelia",
      lastName: "Johnson",
      jobTitle: "cleaner",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "London",
      experience: "0-1 year",
    },
    {
      firstName: "William",
      lastName: "Roberts",
      jobTitle: "bartender",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "London",
      experience: "2-5 years",
    },
    {
      firstName: "Isabella",
      lastName: "Thompson",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "London",
      experience: "10+ years",
    },
    {
      firstName: "Jack",
      lastName: "Harris",
      jobTitle: "manager",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "London",
      experience: "5-10 years",
    },
    {
      firstName: "Charlotte",
      lastName: "Davies",
      jobTitle: "technician",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "London",
      experience: "5-10 years",
    },
    {
      firstName: "Harry",
      lastName: "Wilson",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "London",
      experience: "2-5 years",
    },
    {
      firstName: "Emily",
      lastName: "Taylor",
      jobTitle: "waiter",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "London",
      experience: "0-1 year",
    },
    {
      firstName: "George",
      lastName: "Clark",
      jobTitle: "cleaner",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "London",
      experience: "0-1 year",
    },
    {
      firstName: "Sofía",
      lastName: "García",
      jobTitle: "bartender",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "Madrid",
      experience: "2-5 years",
    },
    {
      firstName: "Daniel",
      lastName: "Hernández",
      jobTitle: "cleaner",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "Madrid",
      experience: "0-1 year",
    },
    {
      firstName: "Lucía",
      lastName: "Martínez",
      jobTitle: "waiter",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "Madrid",
      experience: "0-1 year",
    },
    {
      firstName: "Pablo",
      lastName: "Rodríguez",
      jobTitle: "manager",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "Madrid",
      experience: "5-10 years",
    },
    {
      firstName: "Valeria",
      lastName: "López",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "Madrid",
      experience: "10+ years",
    },
    {
      firstName: "Alejandro",
      lastName: "Gómez",
      jobTitle: "technician",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "Madrid",
      experience: "5-10 years",
    },
    {
      firstName: "María",
      lastName: "Sánchez",
      jobTitle: "chef",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Madrid",
      experience: "10+ years",
    },
    {
      firstName: "Carlos",
      lastName: "Fernández",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "Madrid",
      experience: "2-5 years",
    },
    {
      firstName: "Emma",
      lastName: "Jiménez",
      jobTitle: "waiter",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "Madrid",
      experience: "0-1 year",
    },
    {
      firstName: "Diego",
      lastName: "Ruiz",
      jobTitle: "cleaner",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "Madrid",
      experience: "0-1 year",
    },
    {
      firstName: "Sophie",
      lastName: "Walker",
      jobTitle: "bartender",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "London",
      experience: "2-5 years",
    },
    {
      firstName: "James",
      lastName: "Brown",
      jobTitle: "cleaner",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "London",
      experience: "0-1 year",
    },
    {
      firstName: "Emma",
      lastName: "Robinson",
      jobTitle: "waiter",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "London",
      experience: "0-1 year",
    },
    {
      firstName: "Thomas",
      lastName: "Wilson",
      jobTitle: "manager",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "London",
      experience: "5-10 years",
    },
    {
      firstName: "Olivia",
      lastName: "Taylor",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "London",
      experience: "10+ years",
    },
    {
      firstName: "Jack",
      lastName: "Evans",
      jobTitle: "technician",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "London",
      experience: "5-10 years",
    },
    {
      firstName: "Amelia",
      lastName: "Allen",
      jobTitle: "chef",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "London",
      experience: "10+ years",
    },
    {
      firstName: "Harry",
      lastName: "Thompson",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "London",
      experience: "2-5 years",
    },
    {
      firstName: "Emily",
      lastName: "Carter",
      jobTitle: "waiter",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "London",
      experience: "0-1 year",
    },
    {
      firstName: "George",
      lastName: "Harris",
      jobTitle: "cleaner",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "London",
      experience: "0-1 year",
    },
    {
      firstName: "Elena",
      lastName: "Fernández",
      jobTitle: "bartender",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "Madrid",
      experience: "2-5 years",
    },
    {
      firstName: "David",
      lastName: "González",
      jobTitle: "cleaner",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "Madrid",
      experience: "0-1 year",
    },
    {
      firstName: "Ana",
      lastName: "Martínez",
      jobTitle: "waiter",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "Madrid",
      experience: "0-1 year",
    },
    {
      firstName: "Javier",
      lastName: "López",
      jobTitle: "manager",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "Madrid",
      experience: "5-10 years",
    },
    {
      firstName: "Laura",
      lastName: "Sánchez",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "Madrid",
      experience: "10+ years",
    },
    {
      firstName: "Carlos",
      lastName: "Rodríguez",
      jobTitle: "technician",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "Madrid",
      experience: "5-10 years",
    },
    {
      firstName: "María",
      lastName: "Gómez",
      jobTitle: "chef",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Madrid",
      experience: "10+ years",
    },
    {
      firstName: "Pablo",
      lastName: "Martín",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "Madrid",
      experience: "2-5 years",
    },
    {
      firstName: "Lucía",
      lastName: "Díaz",
      jobTitle: "waiter",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "Madrid",
      experience: "0-1 year",
    },
    {
      firstName: "Alejandro",
      lastName: "Ruiz",
      jobTitle: "cleaner",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "Madrid",
      experience: "0-1 year",
    },
    {
      firstName: "Juliette",
      lastName: "Dupont",
      jobTitle: "bartender",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "Paris",
      experience: "2-5 years",
    },
    {
      firstName: "Nicolas",
      lastName: "Leclerc",
      jobTitle: "cleaner",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Manon",
      lastName: "Dubois",
      jobTitle: "waiter",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Mathieu",
      lastName: "Moreau",
      jobTitle: "manager",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "Paris",
      experience: "5-10 years",
    },
    {
      firstName: "Emma",
      lastName: "Lefèvre",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "Paris",
      experience: "10+ years",
    },
    {
      firstName: "Lucas",
      lastName: "Garnier",
      jobTitle: "technician",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "Paris",
      experience: "5-10 years",
    },
    {
      firstName: "Chloé",
      lastName: "Martin",
      jobTitle: "chef",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Paris",
      experience: "10+ years",
    },
    {
      firstName: "Louis",
      lastName: "Petit",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "Paris",
      experience: "2-5 years",
    },
    {
      firstName: "Charlotte",
      lastName: "Robert",
      jobTitle: "waiter",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Hugo",
      lastName: "Durand",
      jobTitle: "cleaner",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "Paris",
      experience: "0-1 year",
    },
    {
      firstName: "Ayşe",
      lastName: "Kaya",
      jobTitle: "bartender",
      startDate: "03/03/2024",
      endDate: "04/03/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Mustafa",
      lastName: "Arslan",
      jobTitle: "cleaner",
      startDate: "03/18/2024",
      endDate: "04/18/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "Fatma",
      lastName: "Yılmaz",
      jobTitle: "waiter",
      startDate: "03/07/2024",
      endDate: "04/07/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "Mehmet",
      lastName: "Çelik",
      jobTitle: "manager",
      startDate: "03/22/2024",
      endDate: "04/22/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Zeynep",
      lastName: "Demir",
      jobTitle: "performer",
      startDate: "03/13/2024",
      endDate: "04/13/2024",
      location: "Istanbul",
      experience: "10+ years",
    },
    {
      firstName: "Emre",
      lastName: "Şahin",
      jobTitle: "technician",
      startDate: "03/09/2024",
      endDate: "04/09/2024",
      location: "Istanbul",
      experience: "5-10 years",
    },
    {
      firstName: "Seda",
      lastName: "Yıldırım",
      jobTitle: "chef",
      startDate: "03/05/2024",
      endDate: "04/05/2024",
      location: "Istanbul",
      experience: "10+ years",
    },
    {
      firstName: "Ali",
      lastName: "Kurt",
      jobTitle: "chauffeur",
      startDate: "03/16/2024",
      endDate: "04/16/2024",
      location: "Istanbul",
      experience: "2-5 years",
    },
    {
      firstName: "Deniz",
      lastName: "Oğuz",
      jobTitle: "waiter",
      startDate: "03/28/2024",
      endDate: "04/28/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
    {
      firstName: "Elif",
      lastName: "Çakır",
      jobTitle: "cleaner",
      startDate: "03/25/2024",
      endDate: "04/25/2024",
      location: "Istanbul",
      experience: "0-1 year",
    },
  ];
  const filteredStaff = staffListings.filter(
    (job) => job.jobTitle.toLowerCase() === service.toLowerCase()
  );

  return filteredStaff;
};
export default getStaff;
